version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_init_data.js:/docker-entrypoint-initdb.d/mongo_init_data.js:ro

  rest-api:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
